name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ważne, aby pobrać całą historię dla semantic-release
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}